export const countries = [
  { value: "argentina", label: "Argentina", korean: "아르헨티나", flag: "/argentina.png" },
  { value: "australia", label: "Australia", korean: "호주", flag: "/australia.png" },
  { value: "austria", label: "Austria", korean: "오스트리아", flag: "/austria.png" },
  { value: "belgium", label: "Belgium", korean: "벨기에", flag: "/belgium.png" },
  { value: "canada", label: "Canada", korean: "캐나다", flag: "/canada.png" },
  { value: "czechia", label: "Czech Republic", korean: "체코", flag: "/czech republic.png" },
  { value: "denmark", label: "Denmark", korean: "덴마크", flag: "/denmark.png" },
  { value: "france", label: "France", korean: "프랑스", flag: "/france.png" },
  { value: "germany", label: "Germany", korean: "독일", flag: "/germany.png" },
  { value: "hungary", label: "Hungary", korean: "헝가리", flag: "/hungary.png" },
  { value: "ireland", label: "Ireland", korean: "아일랜드", flag: "/ireland.png" },
  { value: "japan", label: "Japan", korean: "일본", flag: "/japan.png" },
  { value: "netherlands", label: "Netherlands", korean: "네덜란드", flag: "/netherlands.png" },
  { value: "newzealand", label: "New Zealand", korean: "뉴질랜드", flag: "/newzealand.png" },
  { value: "poland", label: "Poland", korean: "폴란드", flag: "/poland.png" },
  { value: "portugal", label: "Portugal", korean: "포르투갈", flag: "/portugal.png" },
  { value: "spain", label: "Spain", korean: "스페인", flag: "/spain.png" },
  { value: "sweden", label: "Sweden", korean: "스웨덴", flag: "/sweden.png" },
  { value: "taiwan", label: "Taiwan", korean: "대만", flag: "/taiwan.png" },
  { value: "uk", label: "United Kingdom", korean: "영국", flag: "/united kingdom.png" },
] as const;
