const koreanJobs: Record<string, string> = {
  "카페알바": "barista",
  "카페직원": "cafe worker",
  "바리스타": "barista",
  "주방보조": "kitchen hand",
  "키친핸드": "kitchen hand",
  "주방직원": "kitchen staff",
  "설거지": "dishwasher",
  "요리사": "cook",
  "조리사": "cook",
  "셰프": "chef",
  "제빵": "baker",
  "제빵사": "baker",
  "베이커": "baker",
  "서빙": "waitstaff",
  "홀서빙": "waitstaff",
  "웨이터": "waiter",
  "웨이트리스": "waitress",
  "식당직원": "restaurant staff",
  "레스토랑직원": "restaurant staff",
  "배달": "delivery driver",
  "배달기사": "delivery driver",
  "호텔직원": "hotel staff",
  "농장": "farm hand",
  "농장알바": "farm hand",
  "과일따기": "fruit picker",
  "과수원": "orchard worker",
  "포도농장": "vineyard worker",
  "목장": "farm hand",
  "농산물포장": "produce packer",
  "청소": "cleaner",
  "청소알바": "cleaner",
  "호텔청소": "housekeeper",
  "객실청소": "housekeeper",
  "하우스키핑": "housekeeper",
  "호텔프론트": "hotel receptionist",
  "프론트데스크": "receptionist",
  "리셉션": "receptionist",
  "리조트": "resort staff",
  "창고": "warehouse worker",
  "창고알바": "warehouse worker",
  "피커패커": "picker packer",
  "포장알바": "packer",
  "물류": "logistics worker",
  "지게차": "forklift operator",
  "배송": "delivery driver",
  "운전기사": "driver",
  "공장": "factory worker",
  "생산직": "production worker",
  "조립": "assembly worker",
  "건설": "construction worker",
  "건설현장": "construction worker",
  "현장직": "construction worker",
  "목수": "carpenter",
  "용접": "welder",
  "용접공": "welder",
  "페인터": "painter",
  "도장공": "painter",
  "전기기사": "electrician",
  "배관공": "plumber",
  "조경": "landscaper",
  "정비사": "mechanic",
  "자동차정비": "automotive mechanic",
  "판매직": "retail assistant",
  "매장직원": "retail assistant",
  "캐셔": "cashier",
  "계산원": "cashier",
  "슈퍼마켓": "supermarket assistant",
  "마트직원": "supermarket assistant",
  "베이비시터": "babysitter",
  "보육": "childcare worker",
  "보육교사": "childcare worker",
  "간병": "caregiver",
  "노인돌봄": "aged care worker",
  "사무직": "office administrator",
  "사무보조": "administrative assistant",
  "데이터입력": "data entry",
  "고객센터": "customer service",
  "콜센터": "call centre",
  "개발자": "software developer",
  "웹개발자": "web developer",
  "디자이너": "graphic designer",
  "마케팅": "marketing assistant",
};

export const koreanJobSuggestions = [
  "카페 알바", "주방 보조", "설거지", "요리사", "서빙",
  "호텔 청소", "호텔 프론트", "리조트", "농장", "과일 따기",
  "포도 농장", "창고", "피커 패커", "지게차", "공장", "생산직",
  "건설", "목수", "용접", "자동차 정비", "판매직", "매장 직원",
  "베이비시터", "노인 돌봄", "사무 보조", "고객 센터", "개발자",
];

export function expandKoreanJobQuery(query: string) {
  const trimmed = query.trim();
  return koreanJobs[trimmed.replace(/\s+/g, "")] || trimmed;
}
