// Re-export types from the main types file for backwards compatibility
export type {
  JobType,
  MidType,
  UserType,
  MidTypePopulate,
  LocalizedString,
  UnifiedJob,
  CareerJetJob,
  AdzunaJob,
  JobSearchResponse,
  ApiErrorResponse,
  ApiSuccessResponse,
  ApiResponse,
  ClerkUserData,
  SearchParams,
  JobFilters,
  JobId,
  FilterUpdate,
  JobCategory,
} from "./index";

export {
  CareerJetJobSchema,
  CareerJetResponseSchema,
  AdzunaJobSchema,
  AdzunaResponseSchema,
  MongoDBJobSchema,
  JobFiltersSchema,
  SearchParamsSchema,
  CreateUserSchema,
  SaveJobSchema,
  isLocalizedString,
  isMongoDBJob,
  isCareerJetJob,
  isAdzunaJob,
} from "./index";